version: "3.9"
services:
  web:
    build:
      context: .
      # args:
      #     - NODE_ENV=local
      dockerfile: ./Dockerfile_client
    ports:
      - "52013:52013"
  python_service:
    build:
      context: .
      dockerfile: ./Dockerfile_service
    ports:
      - "8765:8765"
